// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "cacheKeys",
  "cacheKeys.length",
  "configStore.adCustomMomentList",
  "index",
  "item",
  "loading",
  "more"
];
