// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "configStore.adCustomPuzzleRanking",
  "index",
  "item",
  "item.level",
  "item.rank",
  "item.userId",
  "loading",
  "rankings",
  "rankings.length"
];
