services:
  guess-mysql:
    image: mysql:9.1.0
    command: --innodb-buffer-pool-size=32M --innodb_log_buffer_size=512K
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guess
    ports:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  guess-service:
    build: service/guess
    image: guess/service
    depends_on:
      guess-mysql:
        condition: service_healthy
    environment:
      JAVA_OPTS: >
        -Xss512k
        -XX:MaxRAM=260m
        -Dspring.profiles.active=local
        -Dspring.datasource.password=root
        -Dcore.url.db-mysql=jdbc:mysql://guess-mysql/guess?allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"
