// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "cacheKey",
  "index",
  "item",
  "moment.answer",
  "moment.content",
  "moment.correct",
  "moment.created",
  "moment.options",
  "moment.options.length",
  "moment.userId"
];
