// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "configStore.adCustomMomentDetail",
  "loading",
  "moment.cacheKey",
  "moment.comment"
];
