// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "configStore.adCustomPuzzleReply",
  "configStore.preview",
  "content",
  "id",
  "images",
  "item",
  "limit",
  "loading",
  "options"
];
