// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "cacheKey",
  "comment.content",
  "comment.created",
  "user.nickname",
  "user.userId"
];
