// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "activeNames",
  "answer",
  "answers",
  "content",
  "content.length",
  "index",
  "item",
  "loading",
  "optionKeys",
  "optionLen",
  "options"
];
