// generated by `npm run pick`, do not edit manually
/* eslint-disable */
export const PICKS: string[] = [
  "cacheKey",
  "moment.content",
  "moment.created",
  "moment.status",
  "moment.userId"
];
